name: Build and deploy ASP.Net Core app to Azure Web App - LesterMAppServiceDAST

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build solution
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./src/Web/Web.csproj -c Release -o ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: SERVICE_PRINCIPAL
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'LesterMAppServiceDAST'
          slot-name: 'Production'
          package: ./publish
